name: Test PR

on:
    pull_request:
        branches: development

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: npm install, run lint
              run: |
                  npm ci
                  npm run lint
              env:
                  CI: true

            - name: Run Tests
              run: npm test
